name: Build C++ Project (Optional Testing Removed)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set up CMake
        uses: martinlindhe/cmake-action@v1
        with:
          cmakeListsOrSettingsJson: 'CMakeLists.txt'  # Path to your CMakeLists.txt file

      - name: Build
        run: cmake --build . --config Release

